2-sample_app/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'

  get 'help' => 'static_pages#help' 
  get 'contact' => 'static_pages#contact'
  get 'about' => 'static_pages#about'
  get 'signup' => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
end

2-sample_app/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token

  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest. User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

2-sample_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
end

2-sample_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # login
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      remember user
      redirect_to user
    else
      # create error
      flash[:danger] = 'Invalid email/password'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

end

2-sample_app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def contact
  end

  def about
  end
end

2-sample_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find params[:id]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Sample App"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

2-sample_app/app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title='')
    base_title = 'Sample App'
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

end

2-sample_app/app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

end

2-sample_app/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

2-sample_app/app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    g_id = Digest::MD5::hexdigest(user.email.downcase)
    g_url = "https://secure.gravatar.com/avatar/#{g_id}"
    image_tag(g_url, alt: user.name, class: "gravatar")
  end
end

2-sample_app/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Site by Karan Goel.
  </small>
  <nav>
    <ul>
      <li><%= link_to("About", about_path) %></li>
      <li><%= link_to("Contact", contact_path) %></li>
    </ul>
  </nav>
</footer>

2-sample_app/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

2-sample_app/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

2-sample_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class="container">

    <% flash.each do |msg_type, msg| %>
      <div class="alert alert-<%= msg_type %>"><%= msg %></div>
    <% end %>

    <%= yield %>

    <%= render 'layouts/footer' %>
    <%= debug params if Rails.env.development? %>
  
  </div>

</body>
</html>

2-sample_app/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize @user.errors.count, "error" %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

2-sample_app/app/views/static_pages/about.html.erb
<% provide :title, "About"%>

<h1>About</h1>

<p>Lorem ipsum Mollit nulla enim in sit fugiat non incididunt in ad ut laborum nisi in mollit cupidatat dolor nostrud pariatur sit dolore voluptate exercitation dolor irure pariatur deserunt sunt pariatur Ut in Ut do.</p>

<p>Lorem ipsum Nisi officia labore ea qui ea qui officia tempor tempor id magna culpa ea sint laborum ea occaecat laborum dolor enim ut sed cupidatat sit in proident incididunt velit ut dolore tempor tempor reprehenderit nisi ut aliquip Duis voluptate occaecat ut anim laboris est ut eiusmod dolor laborum fugiat nulla qui laborum dolore Excepteur est in quis et et aliqua ex est quis anim ut eu ex Excepteur proident aute cupidatat incididunt ex consectetur elit reprehenderit nostrud ad laboris nostrud exercitation in Duis sunt eu ut dolor Excepteur elit ad consequat ullamco consectetur veniam in proident velit id Ut Ut Ut non id dolor ex dolor dolor irure cillum consequat qui ullamco in amet sunt Excepteur sed cillum dolor laboris ea esse irure ut et ex qui anim do laboris sint cillum dolore enim velit in dolor consequat ad in exercitation id fugiat consectetur nulla nulla sunt aliquip do culpa velit sed aute cupidatat consequat in laboris sed sit enim officia reprehenderit laboris commodo mollit do Excepteur laboris veniam Ut dolore in esse nisi labore dolor amet dolore.</p>

2-sample_app/app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

<h1>Contact</h1>

<%= link_to("Email me", "mailto:karan@goel.io" ) %>

2-sample_app/app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

<h1>Help Page</h1>

<p>You get help here.</p>

2-sample_app/app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<div class="center jumbotron">
  <h1>Sample App</h1>

  <p>
    This is the home page for the sample app.
  </p>

  <%= link_to("sign up now!", signup_path, class: "btn btn-lg btn-primary") %>

</div>

<%= link_to(image_tag("rails.png", alt: "Rails logo"), "#" ) %>

2-sample_app/app/views/users/new.html.erb
<% provide :title, "Sign up" %>

<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

2-sample_app/app/views/users/show.html.erb
<% provide :title, @user.name %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>